Repository kubewarden/safe-labels-policy, pull requests merged in 2023-07, with the labels that each got.

#32 feat: background audit config, severity and category annotations.
  metadata.yml
Labels: kind/enhancement

#36 ci: add release-drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: area/ci

#37 ci: bump github-actions to v3.1.6
  .github/workflows/release.yml
  .github/workflows/test.yml
Labels: area/dependencies, area/ci

#38 Revert "ci: add release-drafter"
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: kind/bug, area/ci
